### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by xxxpandemicxxx** [TehCrucible/G2Gfm.bundle#12]
Issue with channel not responding...i am guessing it is a dns/site link needing updated, anyone know what the updated link is?

**Comment by KenSharp** [comment]
The source website has been redesigned. The code needs to be updated.

**Comment by Twoure** [comment]
Yup, what @KenSharp said.  Working on it right now.  Track my progress [here](https://github.com/Twoure/G2Gfm.bundle/commits/dev).

**Comment by Twoure** [comment]
Done.  Fixed in pull request #13.

**Comment by TehCrucible** [comment]
Merged. Can someone confirm this has fixed issues and I'll close this? I'm overseas and cant test myself.

**Comment by KenSharp** [comment]
Not working here. The episodes are listed but no images and then fail with "channel not responding" when clicking on an episode.

`2016-06-08 21:16:34,254 (7f747effd700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/G2Gfm.bundle/Contents/Code/__init__.py", line 137, in EpisodeDetail
    thumb = page_data.xpath("//div[@id='fullimage']//a/img/@src")[0]
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range`

**Comment by Twoure** [comment]
@KenSharp `Plug-ins-5089475` is the incorrect directory to install channels.  Also from your logs I can see you are not using my updated code.  If you are and it's install within the `Plug-ins` directory, then it seems the old code within the `Plug-ins-5089475` is taking priority.  More info on correct `Plug-ins` directory can be found [here](https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-).

**Comment by KenSharp** [comment]
Oops. That's where the original was. Moved to the correct place and it's working. Won't play on the PC but I assume that's a local problem as there's nothing in the logs.

Good work!

**Comment by Twoure** [comment]
> Won't play on the PC but I assume that's a local problem as there's nothing in the logs.

Plex Web can cause caching issues.  The channel's cache time is 1 hour, so try the Plex Web client in another hour to test or open a private browser to test Plex Web.
