### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by cksodhi** [TehCrucible/G2Gfm.bundle#16]
Everything shows empty. :(

**Comment by KenSharp** [comment]
Indeed. No matter which host is selected.

I see that the website needs you to log in. Is that new?

**Comment by vimemail** [comment]
yes, not working anymore

**Comment by sirmax1** [comment]
cyro.se is not working in plex but it does work using a browser :(

**Comment by craigjaneway** [comment]
Cryo.se is broken and will not allow streams.  The old site is now g2g-fm.com and it's taken over by a pay plan that looks like a scam.  Looks like g2g.fm is gone for good.  No more many named site.  Welcome to the cloud and the New World Order of tyrants.
