### ISSUE TITLE
Channel not responding

### ISSUE THREAD

**Issue by wickitazz22** [TehCrucible/G2Gfm.bundle#17]
None of the TV or Movies will play.

**Comment by pgghub** [comment]
Did you get it to work?

**Comment by craigjaneway** [comment]
The error report on popup says "Sorry, but we can't play this video.  The original video may no longer be available, or it may be in a format that isn't supported."   I can play the videos if I grab the URL from info > xml > video URL and open with Firefox player, but Roku player will not play it.  I have tried different PMS settings and even tried Plex RARflix and different play back options and nothing plays now from g2g.fm.

**Comment by Twoure** [comment]
This is a duplicate issue https://github.com/TehCrucible/G2Gfm.bundle/issues/18.  Refer to https://github.com/TehCrucible/G2Gfm.bundle/issues/18#issuecomment-255570972 for more info.

**Comment by TehCrucible** [comment]
Closing duplicate.
