### ISSUE TITLE
channel not responding 

### ISSUE THREAD

**Issue by xxxpandemicxxx** [TehCrucible/G2Gfm.bundle#4]
Issue with channel not responding when playing from Roku... anyone else having this issue?

**Comment by craigjaneway** [comment]
Simply edit the the code with wordpad and change all the g2g to 4do and then the g2g.fm to 4do.se and save it.  Delete the g2g.bundle in plex and also the references to g2g in cache and data in the plugin-support folder.  Copy and paste the edited version of g2g.fx (now 4do.se) into plugin folder of plex.  Should load everything like the old base_url did.

**Comment by xxxpandemicxxx** [comment]
Thanks Craig!  got it working.

**Comment by craigjaneway** [comment]
Good deal!  I was hoping you'd see my reply. ;)

**Comment by TehCrucible** [comment]
Fixed officially.  Thanks again craigjaneway.

**Comment by aj031679** [comment]
Issue :  Channel not responding while playing on pc (Windows) or  Roku 3  anyone else having this problem.

Thanks
